"""Daily summary entity for tracking user progress and insights."""

from datetime import date, datetime
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class DailySummary(BaseModel):
    """Daily summary of user activity, progress, and AI-generated insights.

    This entity aggregates data from conversations, tasks, goals, and other
    user activities to provide a comprehensive daily overview.
    """

    summary_id: UUID = Field(default_factory=uuid4)
    user_id: str
    date: date

    # Task metrics
    tasks_completed: int = 0
    tasks_created: int = 0
    tasks_pending: int = 0

    # Goal metrics
    goals_updated: list[str] = Field(default_factory=list)  # Goal texts that were updated
    goals_progress_delta: float = 0.0  # Total progress change across all goals

    # Conversation metrics
    conversations_count: int = 0
    messages_sent: int = 0

    # English learning metrics
    english_corrections: int = 0

    # Productivity score (0-100)
    # Based on: completion rate, activity level, goal progress
    productivity_score: float = 0.0

    # AI-generated insights
    top_topics: list[str] = Field(default_factory=list)  # Most discussed topics
    key_achievements: list[str] = Field(default_factory=list)  # What user accomplished
    suggestions: list[str] = Field(default_factory=list)  # Personalized suggestions

    # Summary text generated by LLM
    summary_text: str = ""

    # Metadata
    created_at: datetime = Field(default_factory=datetime.now)

    def calculate_productivity_score(self) -> float:
        """Calculate productivity score based on metrics.

        Returns:
            Float between 0-100 indicating productivity level
        """
        score = 0.0

        # Task completion contributes 40%
        if self.tasks_completed > 0 or self.tasks_pending > 0:
            completion_rate = self.tasks_completed / (self.tasks_completed + self.tasks_pending)
            score += completion_rate * 40

        # Goal progress contributes 30%
        if self.goals_progress_delta > 0:
            # Normalize to 0-30 range (assume max 30% progress per day)
            score += min(self.goals_progress_delta, 30.0)

        # Activity level contributes 30%
        # Assume 5 conversations is "good" activity
        activity_score = min(self.conversations_count / 5.0, 1.0) * 30
        score += activity_score

        self.productivity_score = round(min(score, 100.0), 1)
        return self.productivity_score

    def to_dict(self) -> dict:
        """Convert to dictionary for storage."""
        return {
            "summary_id": str(self.summary_id),
            "user_id": self.user_id,
            "date": self.date.isoformat(),
            "tasks_completed": self.tasks_completed,
            "tasks_created": self.tasks_created,
            "tasks_pending": self.tasks_pending,
            "goals_updated": self.goals_updated,
            "goals_progress_delta": self.goals_progress_delta,
            "conversations_count": self.conversations_count,
            "messages_sent": self.messages_sent,
            "english_corrections": self.english_corrections,
            "productivity_score": self.productivity_score,
            "top_topics": self.top_topics,
            "key_achievements": self.key_achievements,
            "suggestions": self.suggestions,
            "summary_text": self.summary_text,
            "created_at": self.created_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "DailySummary":
        """Create from dictionary."""
        return cls(
            summary_id=UUID(data["summary_id"]),
            user_id=data["user_id"],
            date=date.fromisoformat(data["date"]),
            tasks_completed=data.get("tasks_completed", 0),
            tasks_created=data.get("tasks_created", 0),
            tasks_pending=data.get("tasks_pending", 0),
            goals_updated=data.get("goals_updated", []),
            goals_progress_delta=data.get("goals_progress_delta", 0.0),
            conversations_count=data.get("conversations_count", 0),
            messages_sent=data.get("messages_sent", 0),
            english_corrections=data.get("english_corrections", 0),
            productivity_score=data.get("productivity_score", 0.0),
            top_topics=data.get("top_topics", []),
            key_achievements=data.get("key_achievements", []),
            suggestions=data.get("suggestions", []),
            summary_text=data.get("summary_text", ""),
            created_at=datetime.fromisoformat(data["created_at"]),
        )
